Update install.sh to work with FreeBSD cloud-init
vmware/cloud-init-vmware-guestinfo pull request #3
Opened 2019-04-11 13:01 UTC by dariakts

Hello, 

Here's an update to _install.sh_ script so it would work correctly with FreeBSD (cloud-init configurations are in _/usr/local/etc/cloud_ on FreeBSD).

2019-04-11 14:05 UTC, akutz requested changes
Hi @dariakts,

Thank you so much for the PR! I posted a few comments -- primarily picking of nits. I also suggest using http://shellcheck.net to validate the changes prior to submitting changes to shell scripts. Thanks!

2019-04-11 14:05 UTC, akutz commented on install.sh
> +if [ $(uname) == "Linux" ]; then
Hi @dariakts,

Please place `$(uname)` inside double-quotes, ex. `"$(uname)"`, to prevent unintentional expansion.

2019-04-11 14:05 UTC, akutz commented on install.sh
> +elif [$(uname) == "FreeBSD" ]; then
Hi @dariakts,

This line should be rewritten as:

```shell
elif [ "$(uname)" == "FreeBSD" ]; then
```

Note the space between the opening bracket and the left-hand argument as well as the double-quotes around the left-hand argument.

2019-04-12 07:49 UTC, dariakts commented
Thank you for the reply!

I've made some updates as you suggested. I've also replaced double equals by simple equals as suggested by [http://shellcheck.net](http://shellcheck.net).

```sh
# Configure path for cloud-init configuration
if [ "$(uname)" = "Linux" ]; then
  CLOUD_CONFIG_DIR=/etc/cloud
elif [ "$(uname)" = "FreeBSD" ]; then
  CLOUD_CONFIG_DIR=/usr/local/etc/cloud
else
  echo "unknown os" 1>&2 && exit 1
fi
```

What do you think about it ?

2019-04-14 18:12 UTC, akutz commented
> Thank you for the reply!
> 
> I've made some updates as you suggested. I've also replaced double equals by simple equals as suggested by http://shellcheck.net.
> 
> ```shell
> # Configure path for cloud-init configuration
> if [ "$(uname)" = "Linux" ]; then
>   CLOUD_CONFIG_DIR=/etc/cloud
> elif [ "$(uname)" = "FreeBSD" ]; then
>   CLOUD_CONFIG_DIR=/usr/local/etc/cloud
> else
>   echo "unknown os" 1>&2 && exit 1
> fi
> ```
> 
> What do you think about it ?

Hi @dariakts,

I really appreciate you taking the time to address the feedback. I've got several more ideas, but this works as is, and that's fine for now. Please go ahead and squash your last commit into your first. Once you do that I will merge the PR. Thanks!

2019-04-22 20:27 UTC, dariakts commented
Hello,

It's done :)

2020-06-03 19:48 UTC, akutz commented
Hi @dariakts,

Somehow I missed the update that got back to this. Do you mind fixing the conflict? Once it is, I will happily merge this!

2021-08-11 14:01 UTC, akutz commented
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!

2021-08-11 14:01 UTC, closed without merging